name: Deploy process on Pull Request

on:
  pull_request_target:
    types: [opened, synchronize]

  push:
    branches:
      - 'develop'

jobs:
  build:
    if: github.event.pull_request.merged == false
    name: Develop build for demo files
    uses: ./.github/workflows/build.yml
    with:
      cache_sha: ${{ github.event.pull_request.head.sha || github.sha }}

  deploy-pages:
    needs: [build]
    if: github.event.pull_request.merged == false
    name: Deploy the files
    uses: ./.github/workflows/deploy.yml
    with:
      cache_sha: ${{ github.event.pull_request.head.sha || github.sha }}
      folder: ${{github.head_ref}}
