name: Deploy process on Pull Request

on:
  pull_request_target:
    types: [opened, synchronize, closed]

  push:
    branches:
      - 'develop'

jobs:
  check-member:
    name: Check if we continue the process
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR info
        run: |
          echo User ${{ github.actor }} is about to ${{ github.event.action }} on this Pull Request.

      - name: Check if contributor is an org member
        id: is_organization_member
        if: github.event_name == 'pull_request_target'
        uses: JamesSingleton/is-organization-member@1.0.1
        with:
          organization: Canadian-Geospatial-Platform
          username: ${{ github.event.pull_request.head.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output comment and end build if not org member
        if: github.event_name == 'pull_request_target'
        run: |
            result=${{ steps.is_organization_member.outputs.result }}
            if [ $result == false ]; then
              user=${{ github.event.pull_request.head.user.login }}
              echo Either ${user} is not part of the Canadian-Geospatial-Platform organization
              echo or ${user} has its Organization Visibility set to Private at
              echo https://github.com/orgs/Canadian-Geospatial-Platform/people?query=${user}
              exit 1
            fi

      - name: Develop build for demo files
        uses: ./.github/workflows/build.yml
        with:
          cache_sha: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Deploy the files for PR
        if: github.event.pull_request.merged == false
        uses: ./.github/workflows/deploy.yml
        with:
          cache_sha: ${{ github.event.pull_request.head.sha || github.sha }}
          folder: ${{github.head_ref}}

      - name: Deploy the files on public demo
        if: github.event.pull_request.merged == true
        uses: ./.github/workflows/deploy.yml
        with:
          cache_sha: ${{ github.event.pull_request.head.sha || github.sha }}
          folder: public
